version: '3.8'
services:
  selenoid:
    image: aerokube/selenoid:latest
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid:/etc/selenoid"
    command: ["-limit", "5", "-timeout", "3m"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    network_mode: bridge
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
